const food = [
    { name: "Chicken Teriyaki", price: 12.99, meal: "entree", vegan: false, img: "/teriyaki_chicken.webp"},
    { name: "Beef Teriyaki", price: 12.99, meal: "entree", vegan: false, img: "/beef_teriyaki.jpg" },
    { name: "Avocado Salad", price: 7.99, meal: "salad", vegan: true, img: "/avo_salad.jpg"}, 
    { name: "Ginger Salad", price: 3.99, meal: "salad", vegan: true},
    { name: "Beef Negimaki", price: 8.99, meal: "appetizer", vegan: false, img: "/beef_negimaki.jpg" },
    { name: "Spicy Tuna Roll", price: 4.99, meal: "sushi", vegan: false, img: "/spicy_tuna_roll.jpg" },
    { name: "Tuna Roll", price: 4.99, meal: "sushi", vegan: false},
    { name: "AAC Roll", price: 4.99, meal: "sushi", vegan: true},
    { name: "Sweet Potato Roll", price: 4.99, meal: "sushi", vegan: true}, 
    { name: "California Roll", price: 4.99, meal: "sushi", vegan: false},   
    { name: "Shrimp Tempura Roll", price: 6.99, meal: "sushi", vegan: false}, 
    { name: "Miso Soup", price: 2.99, meal: "soup", vegan: true, img: "/miso_soup.jpg"}, 
    { name: "Clear Soup", price: 2.99, meal: "soup", vegan: true},
    { name: "Tom Yum Soup", price: 5.99, meal: "soup", vegan: false},
    { name: "Coconut Soup", price: 5.99, meal: "soup", vegan: false},
    { name: "Fried Rice", price: 11.99, meal: "entree", vegan: false, img: "/Fried_rice.jpg"}, 
    { name: "Poke Bowl", price: 15.99, meal: "entree", vegan: false},
    { name: "Bubble Tea", price: 6.40, meal: "drink", vegan: false}, 
    { name: "Mango Iced Tea", price: 4.99, meal: "drink", vegan: true},
    { name: "Japanese Soda", price: 2.99, meal: "drink", vegan: true},
    { name: "Thai Iced Tea", price: 5.99, meal: "drink", vegan: false},   
    { name: "Crepe Cake", price: 8.99, meal: "dessert", vegan: false}, 
    { name: "Ice Cream", price: 4.99, meal: "dessert", vegan: false},
    { name: "Oreo Donut", price: 6.99, meal: "dessert", vegan: false},  
    { name: "Pork Dumplings", price: 7.99, meal: "appetizer", vegan: false},
    { name: "Spicy Kani Salad", price: 4.99, meal: "salad", vegan: false, img: "/spicy_kani_salad.jpg"},
    { name: "Veggie Dumplings", price: 7.99, meal: "appetizer", vegan: true},
    { name: "Edamame", price: 4.99, meal: "appetizer", vegan: true}, 
    { name: "Dragon Balls", price: 12.99, meal: "appetizer", vegan: false,img: "/dragon_balls.jpg"},
  ]

  export{food};